install: "./ci/install_deps.sh"
language: c
script: "./ci/run_tests.sh"
os:
        - linux
        - osx
compiler:
        - clang
        - gcc
env:
        - BUILD_TYPE=RelWithDebInfo
        - BUILD_TYPE=RelWithDebInfo
# gcc is symlinked to clang on OSX - could install with homebrew and fiddle
# with paths to make sure the one we want is being used, but save that for
# another day if interest arises
matrix:
    exclude:
        - os: osx
          compiler: gcc
